name: autumn_herbarium
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  audioplayers: ^3.0.1
  vibration: ^1.7.6
  shared_preferences: ^2.0.18
  flame: ^1.6.0
  google_fonts: ^4.0.3
  flame_svg: ^1.7.1
  flutter_svg: ^1.0.3

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1


flutter_gen:
  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true

  assets:
    - assets/audios/
    - assets/images/
    - assets/images/menu/
    - assets/images/settings/
    - assets/images/info/
    - assets/images/gameover/
    - assets/images/game/